### ISSUE TITLE
Migrate out from Meteor.com

### ISSUE THREAD

**Issue by simison** [guaka/radio-meteor#62]
This:
>As we mentioned last week, Meteor Development Group will be retiring the legacy Meteor.com free hosting service on March 25, 2016. 
>
>
>How do I migrate my Meteor.com app to another hosting service?
>
>
>Before March 25, 2016 12pm PDT, please migrate your app from the free Meteor.com hosting service to another app hosting platform to ensure continued availability of your app. You will also have until April 15, 2016 12pm PDT to retrieve data from your app’s Mongo database. Here are specific instructions on [how to migrate your Meteor app as well as access your data from the Meteor.com free hosting service](http://go.meteor.com/rs/627-RVJ-941/images/Meteor.com%20Hosting%20Migration%20Guide.pdf).
>
>
>If you want stable, pay-as-you-go hosting for your Meteor app, we recommend using Galaxy (pricing starts at USD $0.035 per container hour). [If you signup for a new Galaxy account](https://www.meteor.com/galaxy/signup) and migrate your app by March 25, you’ll receive a $25 credit (use promo code MARCH25). This credit will provide a new home for your app at *.meteorapp.com and let you experience proven features that help developers build better Meteor apps. 
>
>If you’re only looking for free hosting, we recommend using a combination of free services from Heroku and MongoLab. Here are links to some community articles to help you get started:
>
>- [How to run a MeteorJS application on Heroku in 10 steps](https://medium.com/@leonardykris/how-to-run-a-meteor-js-application-on-heroku-in-10-steps-7aceb12de234)
>- [Deploy to production on Heroku](http://justmeteor.com/blog/deploy-to-production-on-heroku/)
>
>You can also consult the [Meteor Guide for other DIY deployment options](http://guide.meteor.com/deployment.html).
>
>
>-Meteor Development Group

So Heroku sounds like a way to go.

**Comment by guaka** [comment]
setting it up with Heroku, URL will be http://radio.guaka.org/

**Comment by simison** [comment]
Thx :+1:

**Comment by simison** [comment]
Man I use this tool daily and got quite a few friends into it as well. :-) It's pretty awesome!
